Use dasel

diff --git a/cargo-set-dependency/action.yml b/cargo-set-dependency/action.yml
--- a/cargo-set-dependency/action.yml
+++ b/cargo-set-dependency/action.yml
@@ -6,18 +6,24 @@ inputs:
   package:
     description: "Dependency name"
     required: true
-  substitute:
-    description: "Substitute to pass to sed"
+  version:
+    description: "Dependency version"
     required: true
 
 runs:
   using: composite
 
   steps:
+    - name: Setup dasel
+      uses: allejo/setup-dasel@v1
+
     - name: Set ${{ inputs.package }} version
       shell: bash
       run: |
-        sed -i 's#\(${{ inputs.package }} =\) .*#\1 ${{ inputs.substitute }}#g' Cargo.toml
+        version=$(echo '${{ inputs.version }}' | dasel -p json --format '{ {{ $first := true }}{{ range $k, $v := . }}{{ if $first }}{{ $first = false }}{{ else }}, {{ end }}{{ $k }} = "{{ $v }}"{{ end }} }')
+
+        sed -i "s#${{ inputs.package }} = .*#${{ inputs.package }} = \\${version}#g" Cargo.toml
+        cat Cargo.toml
 
     - name: Update Cargo.lock
       shell: bash
@@ -25,18 +31,34 @@ runs:
         CARGO_UNSTABLE_SPARSE_REGISTRY: true
       run: cargo update -p ${{ inputs.package }}
 
-    - name: Install cargo-lock
-      uses: baptiste0928/cargo-install@v1
-      with:
-        crate: cargo-lock
-        features: cli
-
     - name: Fail if more than one source found
       shell: bash
       run: |
-        SOURCES=$(cargo lock list -s -p ${{ inputs.package }})
+        # Fail if more than one source found
+        # get all dependency sources
+        SOURCES=$(dasel -f Cargo.lock -p toml "package.(name=${{ inputs.package }}).source" -m)
         echo $SOURCES
         if (( $(echo $SOURCES | wc -l) > 1 )); then
-          echo "More than one source found"
+          cat <<-ERROR
+          More than one source found.
+          ${{ inputs.package }} should be set in root Cargo.toml file for all
+          workspace members with "workspace.dependency".
+        ERROR
           exit 1
         fi
+
+    - name: Check that ${{ inputs.package }} source found in Cargo.lock matches input
+      shell: bash
+      run: |
+        # Check that ${{ inputs.package }} source found in Cargo.lock matches input
+        # get dependency source
+        SOURCE=$(dasel -f Cargo.lock -p toml "package.(name=${{ inputs.package }}).source" -m)
+        # flatten values from provided json
+        INPUT=$(echo '${{ inputs.version }}' | dasel -p json -m -w plain '.[*]')
+        # check that each value is found in dependency source
+        for param in $INPUT; do
+          if ! [[ $SOURCE =~ $param ]]; then
+            echo "$param not found in $SOURCE"
+            exit 1
+          fi
+        done
